[package]
name = "grok-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
reqwest = "0.12.19"
serde_json = "1.0.140"
serenity = "0.12.4"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
